#ifndef LINGGO_ERROR_HPP
#define LINGGO_ERROR_HPP
#pragma once

enum LINGGO_CODE {
  LINGGO_OK,
  LINGGO_INVALID_CONFIG_PATH,
  LINGGO_INVALID_VOC_PATH,
  LINGGO_INVALID_CONFIG,
  LINGGO_INVALID_VOC,
  LINGGO_INVALID_PARAM,
  LINGGO_OUT_OF_MEMORY,
  LINGGO_UNEXPECTED_ERROR,
  LINGGO_NOT_FOUND,
  LINGGO_USER_NOT_FOUND,
  LINGGO_WRONG_PASSWORD,
};

#endif