#ifndef LINGGO_ERROR_HPP
#define LINGGO_ERROR_HPP
#pragma once

enum LINGGO_CODE
{
  LINGGO_OK,
  LINGGO_INVALID_CONFIG_PATH,
  LINGGO_INVALID_CONFIG,
  LINGGO_INVALID_VOC_PATH,
  LINGGO_INVALID_VOC,
  LINGGO_INVALID_DB,
  LINGGO_INVALID_DB_PATH,
  LINGGO_OUT_OF_MEMORY,
  LINGGO_USER_NOT_FOUND,
  LINGGO_WRONG_PASSWORD,
  LINGGO_INVALID_USER,
  LINGGO_AIGEN_QUIZ_ERROR,
  LINGGO_UNEXPECTED_ERROR,
};

const char* linggo_strerror(enum LINGGO_CODE code);

#endif
